
website(document).ready(function(){website('.datepicker').bootstrapMaterialDatePicker({time:false,clearButton:true,format:'DD/MM/YYYY'});website("#addprojectvalidate").validate({rules:{apclientname:{required:true},aptypeofwork:{required:true},aprefno:{required:true},approjdate:{required:true},apcasename:{required:true}},messages:{apclientname:{required:"Select Client name"},aptypeofwork:{required:"Select Typeofwork"},aprefno:{required:"Enter Reference No"},approjdate:{required:"Select Project Date"},apcasename:{required:"Enter Case name"}},errorPlacement:function(error,element){var name=website(element).attr("name");console.log("this is name");console.log(name);website(element).attr("placeholder",error.text());website(element).addClass('invalid');setTimeout(function(){website(element).removeClass('invalid');website(element).removeClass('valid');},1000);},submitHandler:function(form){website(form).ajaxSubmit({type:"POST",data:website(form).serialize(),dataType:"json",success:function(response){if(response.logged==true){console.log("hllo true");}
else if(response.logged==false){console.log("hllo false");}}});}});website('.addclelemnt').click(function(){var getcount=website(this).attr('cuntcontact');var getcountch=website('.appendcontactdet').attr('cuntcontact');if((getcount===0||getcount<4)&&(getcountch===0||getcountch<4))
{var appendhtmlemail='';var incrementval=parseInt(getcount)+1;if(document.getElementById("newcontactfield-"+incrementval)){incrementval=parseInt(getcount);}else{incrementval=parseInt(getcount)+1;}
appendhtmlemail+='<section class="col col-3" id="newcontactfield-'+incrementval+'">';appendhtmlemail+='<label class="input">';appendhtmlemail+='<i class="icon-append fa fa-user"></i>';appendhtmlemail+='<input type="text" placeholder="Enter Contact Number '+incrementval+'" class="gettaninfo datepicker" id="extra_contactget_id-'+incrementval+'" name="gettaninfo[]">';appendhtmlemail+='<b class="tooltip tooltip-top-right">Contact no. '+incrementval+'</b>';appendhtmlemail+='</label><i class="icon-append fa fa-close iclick" universal="newcontactfield-'+incrementval+'"></i>';appendhtmlemail+='</section>';website('.appendcontactdet').append(appendhtmlemail);website(this).attr('cuntcontact',parseInt(getcount)+1);website('.appendcontactdet').attr('cuntcontact',parseInt(getcount)+1);website(this).removeClass('disabled');}
else
{var html='<label class="input" ><i class="fa fa-warning floatleft faicontri"></i>You can provide only 4 more contacts';website('.extracontact_div').fadeIn('fast');website('.extracontact_div').fadeIn('fast').html(html).delay(1000).fadeOut('slow');setTimeout(function(){website('.extracontact_div').html('');},1000);website(this).addClass('disabled');}});website('.addemelemnt').click(function(){var getcount=website(this).attr('cuntemail');var getcountch=website('.appendemdet').attr('cuntemail');if((getcount===0||getcount<4)&&(getcountch===0||getcountch<4))
{var appendhtmlemail='';var incrementval=parseInt(getcount)+1;if(document.getElementById("newemailfield-"+incrementval)){incrementval=parseInt(getcount);}else{incrementval=parseInt(getcount)+1;}
appendhtmlemail+='<section class="col col-3" id="newemailfield-'+incrementval+'">';appendhtmlemail+='<label class="input">';appendhtmlemail+='<i class="icon-append fa fa-user"></i>';appendhtmlemail+='<input type="text" placeholder="Enter Email '+incrementval+'" class="gettaninfo datepicker" id="extra_emailget_id-'+incrementval+'" name="geteminfo[]">';appendhtmlemail+='<b class="tooltip tooltip-top-right">Email id. '+incrementval+'</b>';appendhtmlemail+='</label><i class="icon-append fa fa-close iclick" universal="newemailfield-'+incrementval+'"></i>';appendhtmlemail+='</section>';website('.appendemdet').append(appendhtmlemail);website(this).attr('cuntemail',parseInt(getcount)+1);website('.appendemdet').attr('cuntemail',parseInt(getcount)+1);website(this).removeClass('disabled');}
else
{var html='<label class="input" ><i class="fa fa-warning floatleft faicontri"></i>You can provide only 4 more emails';website('.extraemail_div').fadeIn('fast');website('.extraemail_div').fadeIn('fast').html(html);setTimeout(function(){website('.extraemail_div').html('');},1000);website(this).addClass('disabled');}});website('body').on('click','.appendcontactdet .iclick',function(){var getid=website(this).attr('universal');website('.rajuharryironman-form .appendcontactdet').find('#'+getid).remove();});website('body').on('click','.appendemdet .iclick',function(){var getid=website(this).attr('universal');console.log("this is email");console.log(getid);website('.rajuharryironman-form .appendemdet').find('#'+getid).remove();});website("a[data-toggle=modal]").click(function()
{website('#editproject .modal-content .emptymodal').empty();website('#editproject .modal-content .emptymodal').val();var projectid=website(this).data('id');website.ajax({cache:false,type:'POST',url:'project/addproject',data:{'projectid':projectid},success:function(response)
{if(response){for(var i=0;i<response.clientdetail.length;i++){cid=response.clientid;if(cid==response.clientdetail[i].id){console.log("this is client name");console.log(response.clientdetail[i].name);website('.modal-content #apclientname').append(website('<option>',{value:cid+'_'+(clean_string_alt(response.clientdetail[i].name)),text:clean_string_alt(response.clientdetail[i].name),selected:'selected'}));}
else{website('.modal-content #apclientname').append(website('<option>',{value:response.clientdetail[i].id+'_'+(clean_string_alt(response.clientdetail[i].name)),text:clean_string_alt(response.clientdetail[i].name)}));}}
for(var i=0;i<response.getworkdetail.length;i++){wid=response.workid;if(wid==response.getworkdetail[i].id){website('.modal-content #aptypeofwork').append(website('<option>',{value:wid+'_'+(clean_string_alt(response.getworkdetail[i].name)),text:clean_string_alt(response.getworkdetail[i].name),selected:'selected'}));}
else{website('.modal-content #aptypeofwork').append(website('<option>',{value:response.getworkdetail[i].id+'_'+(clean_string_alt(response.getworkdetail[i].name)),text:clean_string_alt(response.getworkdetail[i].name)}));}}
for(var i=0;i<response.getdocdetail.length;i++){if(response.paper){website.each(response.paper,function(key,val){papid=val.id;if(papid==response.getdocdetail[i].id){website('.modal-content #apnameofpaper').append(website('<option>',{value:papid,text:clean_string_alt(response.getdocdetail[i].name),selected:'selected'}));return false;}});}
website('.modal-content #apnameofpaper').append(website('<option>',{value:response.getdocdetail[i].id,text:clean_string_alt(response.getdocdetail[i].name)}));}
for(var i=0;i<response.getservicedetail.length;i++){if(response.service){website.each(response.service,function(key,val){serid=val.id;if(serid==response.getservicedetail[i].id){website('.modal-content #apservice').append(website('<option>',{value:serid,text:clean_string_alt(response.getservicedetail[i].name),selected:'selected'}));return false;}});}
website('.modal-content #apservice').append(website('<option>',{value:response.getservicedetail[i].id,text:clean_string_alt(response.getservicedetail[i].name)}));}
for(var i=0;i<response.getempdetail.length;i++){if(response.employee){website.each(response.employee,function(key,val){empid=val.id;if(empid==response.getempdetail[i].id){website('.modal-content #apemp').append(website('<option>',{value:empid,text:clean_string_alt(response.getempdetail[i].name),selected:'selected'}));return false;}});}
website('.modal-content #apemp').append(website('<option>',{value:response.getempdetail[i].id,text:clean_string_alt(response.getempdetail[i].name)}));}
for(var i=0;i<response.getclerkdetail.length;i++){if(response.clerk){website.each(response.clerk,function(key,val){clerkid=val.id;if(clerkid==response.getclerkdetail[i].id){website('.modal-content #apclerk').append(website('<option>',{value:clerkid,text:clean_string_alt(response.getclerkdetail[i].name),selected:'selected'}));return false;}});}
website('.modal-content #apclerk').append(website('<option>',{value:response.getclerkdetail[i].id,text:clean_string_alt(response.getclerkdetail[i].name)}));}
for(var i=0;i<response.getdocboydetail.length;i++){if(response.docboy){website.each(response.docboy,function(key,val){dbid=val.id;if(dbid==response.getdocboydetail[i].id){website('.modal-content #apdocboy').append(website('<option>',{value:dbid,text:clean_string_alt(response.getdocboydetail[i].name),selected:'selected'}));return false;}});}
website('.modal-content #apdocboy').append(website('<option>',{value:response.getdocboydetail[i].id,text:clean_string_alt(response.getdocboydetail[i].name)}));}
website('.modal-content #approjdate').val(response['mainarr'].projectdate);website('.modal-content #apcasename').val(response['mainarr'].casename);website('.modal-content #aprefno').val(response['mainarr'].refno);website('.modal-content #apsoftcopy').val(response['mainarr'].softcopy);website('.modal-content #aphardcopy').val(response['mainarr'].hardcopy);website('.modal-content #appendingdocs').val(response['mainarr'].pendingdocs);website('.modal-content #apsearchrcv').val(response['mainarr'].searchrcvd);website('.modal-content #apdocsrcv').val(response['mainarr'].docsrcvd);website('.modal-content #apsearchini').val(response['mainarr'].searchini);website('.modal-content #apfrepsent').val(response['mainarr'].finalrepsent);website('.modal-content #aprecsearch').val(response['mainarr'].receiptsearch);website('.modal-content #apprice').val(response['mainarr'].price);website('.modal-content #aptotalamt').val(response['mainarr'].totalamount);website('.modal-content #apbranch').val(response['mainarr'].branch);website('.modal-content #apapsid').val(response['mainarr'].apsid);website('.modal-content #apstatus').val(response['mainarr'].status);website('.modal-content #aprmanager').val(response['mainarr'].rm);website('.modal-content #appropaddr').val(response['mainarr'].propaddress);website('.modal-content #apremark').val(response['mainarr'].remarks);website('.modal-content #projid').val(response['mainarr'].id);if(response['mainarr'].approve==1){website('.modal-content #apapprove').prop('checked',true);}
else{website('.modal-content #apapprove').prop('checked',false);}
if(response['mainarr'].externalwork==1){website('.modal-content #apextwrkreq').prop('checked',true);}
else{website('.modal-content #apextwrkreq').prop('checked',false);}
if(response['mainarr'].searchreq==1){website('.modal-content #apsearchreq').prop('checked',true);}
else{website('.modal-content #apsearchreq').prop('checked',false);}
if(response['mainarr'].servicetax==1){website('.modal-content #aptaxreq').prop('checked',true);}
else{website('.modal-content #aptaxreq').prop('checked',false);}
website('.modal-content').show();var clientid=website('.modal-content #apclientname option:selected').val();var serviceid=[];website('#apservice option:selected').each(function(){serviceid.push(website(this).val());});if(clientid){checkservice(clientid);}
if(clientid&&serviceid&&serviceid.length>0){checkpricedetails(clientid,serviceid);}}
else{console.log("hllo false");}}});});function clean_string(str){return str.replace(/[^a-zA-Z0-9]\s+/g,' ');}
function clean_string_alt(str){return str.replace(/[^a-zA-Z0-9]+/g,' ');}
function checkpricedetails(clientid,serviceid)
{website.ajax({url:'project/getserviceprice',data:{'clientid':clientid,'serviceid':serviceid},type:'POST',dataType:'json',success:function(result){if(result)
{website.each(result,function(key,val){website('#apprice').val(val.price);var total=parseFloat(val.price);website('.modal-content #aptotalamt').val(total);});}}});}
function checkpricedetailsap(clientid,serviceid)
{console.log("in here");website.ajax({url:'project/getserviceprice',data:{'clientid':clientid,'serviceid':serviceid},type:'POST',dataType:'json',success:function(result){if(result)
{website.each(result,function(key,val){website('#apprice').val(val.price);var total=parseFloat(val.price);website('#aptotalamt').val(total);});}
else{website('#apprice').val('');website('#aptotalamt').val('');}}});}
function checkservice(clientid){if(clientid){website.ajax({url:'project/getservices',data:{'clientid':clientid},type:'POST',dataType:'json',success:function(result){if(result)
{website(".modal-content #apservice").empty();for(var i=0;i<result.length;i++){website('.modal-content #apservice').append(website('<option>',{value:result[i].id,text:result[i].name}));}}}});}}
function checkserviceap(clientid){if(clientid){website.ajax({url:'project/getservices',data:{'clientid':clientid},type:'POST',dataType:'json',success:function(result){if(result)
{console.log("this is result");console.log(result);website("#addprojectvalidate #apservice").empty();for(var i=0;i<result.length;i++){website('#addprojectvalidate #apservice').append(website('<option>',{value:result[i].id,text:result[i].name}));}}}});}}
website('.modal-content .priceelement').on('change',function(){var clientid=website('#apclientname option:selected').val();var serviceid=[];checkservice(clientid);website('#apservices option:selected').each(function(){serviceid.push(website(this).val());});console.log("this is clientid");console.log(clientid);if(clientid&&serviceid&&serviceid.length>0){console.log("in right place");checkpricedetails(clientid,serviceid);}});website('.clientservicesget').on('change',function(){var clientid=website('#apclientname option:selected').val();var serviceid=[];checkserviceap(clientid);website('#apservices option:selected').each(function(){serviceid.push(website(this).val());});console.log("this is clientid");console.log(clientid);if(clientid&&serviceid&&serviceid.length>0){console.log("in right place");checkpricedetailsap(clientid,serviceid);}
else{website('#apprice').val('');website('#aptotalamt').val('');}});website('.apserviceprice').on('change',function(){var clientid=website('#apclientname option:selected').val();var serviceid=[];website('#apservice option:selected').each(function(){serviceid.push(website(this).val());});if(clientid&&serviceid&&serviceid.length>0){checkpricedetailsap(clientid,serviceid);}
else{website('#apprice').val('');website('#aptotalamt').val('');}});website(".select2_multiple").select2({placeholder:"With Max Selection",allowClear:true});});;