
(function(window){'use strict';function classReg(className){return new RegExp("(^|\\s+)"+className+"(\\s+|$)");}
var hasClass,addClass,removeClass;if('classList'in document.documentElement){hasClass=function(elem,c){return elem.classList.contains(c);};addClass=function(elem,c){elem.classList.add(c);};removeClass=function(elem,c){elem.classList.remove(c);};}
else{hasClass=function(elem,c){return classReg(c).test(elem.className);};addClass=function(elem,c){if(!hasClass(elem,c)){elem.className=elem.className+' '+c;}};removeClass=function(elem,c){elem.className=elem.className.replace(classReg(c),' ');};}
function toggleClass(elem,c){var fn=hasClass(elem,c)?removeClass:addClass;fn(elem,c);}
var classie={hasClass:hasClass,addClass:addClass,removeClass:removeClass,toggleClass:toggleClass,has:hasClass,add:addClass,remove:removeClass,toggle:toggleClass};if(typeof define==='function'&&define.amd){define(classie);}else{window.classie=classie;}})(window);;;(function(window){'use strict';function extend(a,b){for(var key in b){if(b.hasOwnProperty(key)){a[key]=b[key];}}
return a;}
var support={transitions:''},transEndEventNames={'WebkitTransition':'webkitTransitionEnd','MozTransition':'transitionend','OTransition':'oTransitionEnd','msTransition':'MSTransitionEnd','transition':'transitionend'},transEndEventName=transEndEventNames[''];function ProgressButton(el,options){this.button=el;this.options=extend({},this.options);extend(this.options,options);this._init();}
ProgressButton.prototype.options={statusTime:1500};ProgressButton.prototype._init=function(){this._validate();this._create();this._initEvents();};ProgressButton.prototype._validate=function(){if(this.button.getAttribute('data-style')===null){this.button.setAttribute('data-style','fill');}
if(this.button.getAttribute('data-vertical')===null&&this.button.getAttribute('data-horizontal')===null){this.button.setAttribute('data-horizontal','');}
if(!support.transforms3d&&this.button.getAttribute('data-perspective')!==null){this.button.removeAttribute('data-perspective');this.button.setAttribute('data-style','fill');this.button.removeAttribute('data-vertical');this.button.setAttribute('data-horizontal','');}};ProgressButton.prototype._create=function(){var textEl=document.createElement('span');textEl.className='content';textEl.innerHTML=this.button.innerHTML;var progressEl=document.createElement('span');progressEl.className='progress';var progressInnerEl=document.createElement('span');progressInnerEl.className='progress-inner';progressEl.appendChild(progressInnerEl);this.button.innerHTML='';if(this.button.getAttribute('data-perspective')!==null){var progressWrapEl=document.createElement('span');progressWrapEl.className='progress-wrap';progressWrapEl.appendChild(textEl);progressWrapEl.appendChild(progressEl);this.button.appendChild(progressWrapEl);}
else{this.button.appendChild(textEl);this.button.appendChild(progressEl);}
this.progress=progressInnerEl;if(this.button.getAttribute('data-horizontal')!==null){this.progressProp='width';}
else if(this.button.getAttribute('data-vertical')!==null){this.progressProp='height';}
this._enable();};ProgressButton.prototype._setProgress=function(val){this.progress.style[this.progressProp]=100*val+'%';};ProgressButton.prototype._initEvents=function(){var self=this;this.button.addEventListener('click',function(){self.button.setAttribute('disabled','');classie.remove(self.progress,'notransition');classie.add(this,'state-loading');setTimeout(function(){if(typeof self.options.callback==='function'){self.options.callback(self);}
else{self._setProgress(1);var onEndTransFn=function(ev){if(support.transitions&&ev.propertyName!==self.progressProp)return;this.removeEventListener(transEndEventName,onEndTransFn);self._stop();};if(support.transitions){self.progress.addEventListener(transEndEventName,onEndTransFn);}
else{onEndTransFn.call();}}},self.button.getAttribute('data-style')==='fill'||self.button.getAttribute('data-style')==='top-line'||self.button.getAttribute('data-style')==='lateral-lines'?0:200);});};ProgressButton.prototype._stop=function(status){var self=this;setTimeout(function(){self.progress.style.opacity=0;var onEndTransFn=function(ev){if(support.transitions&&ev.propertyName!=='opacity')return;classie.add(self.progress,'notransition');self.progress.style[self.progressProp]='0%';self.progress.style.opacity=1;};if(support.transitions){self.progress.addEventListener(transEndEventName,onEndTransFn);}
else{onEndTransFn.call();}
if(typeof status==='number'){var statusClass=status>=0?'state-success':'state-error';classie.add(self.button,statusClass);setTimeout(function(){classie.remove(self.button,statusClass);self._enable();},self.options.statusTime);}
else{self._enable();}
classie.remove(self.button,'state-loading');},100);};ProgressButton.prototype._enable=function(){this.button.removeAttribute('disabled');}
window.ProgressButton=ProgressButton;})(window);;